language: objective-c
script:
  - xctool test -scheme PMDate ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
  
xcode_project: PMDate.xcodeproj
xcode_scheme: PMDate